### ISSUE TITLE
How to use NestedTreeGrid

### ISSUE THREAD

**Issue by gemilangpermata** [dkhlystov/yii2-treegrid#4]
I'm trying to use this widget, but when expanding a row, grid incorrectly loads new row.
![image](https://cloud.githubusercontent.com/assets/9245589/22427998/eaa54fbe-e737-11e6-8a78-de5d4567d898.png)
![image](https://cloud.githubusercontent.com/assets/9245589/22428015/f9d62f62-e737-11e6-89d4-a53995530ac2.png)

My DataProvider:
![image](https://cloud.githubusercontent.com/assets/9245589/22428054/332474e0-e738-11e6-9796-574694556b35.png)

and my view:
![image](https://cloud.githubusercontent.com/assets/9245589/22428088/5453be96-e738-11e6-9bd0-77c3dc7989d9.png)

**Comment by dkhlystov** [comment]
Post your data please
